### ISSUE TITLE
Removing Hours Line

### ISSUE THREAD

**Issue by lieselvink** [RockefellerArchiveCenter/scripts#24]
**Is your feature request related to a problem? Please describe.**
No, it is not related to a problem.

**Describe the solution you'd like**
As discussed with Bonnie, it would be great if the start time in hours was removed. It's rarely used. 

**Describe alternatives you've considered**
For now, I enter "0" when I come to that line.

**Additional context**

**Comment by bonniegee** [comment]
Since the "hours" input is rarely used, the user often inputs the minutes during the hours prompt. The current workaround is to quit the script. There are two types of solutions to this:

-    allow the user to "undo" the previous user prompt or add a verification prompt
-    automatically calculate the duration of the video; if the video is < 1 hour, do not prompt for hours in start time; if the video is > 1 hour, prompt for hours in the start time and do not accept a value greater than the total number of hours

While ideally both fixes would be implemented, the second fix is easier and would substantially reduce user error.
