### ISSUE TITLE
Time Data Incorrect

### ISSUE THREAD

**Issue by lieselvink** [RockefellerArchiveCenter/scripts#28]
**Describe the bug**
The data in both the start time and duration time are incorrect in the spreadsheet. The data now appears as a decimal. 

**To reproduce**
1. Go to S:\RAC_AV_CLIPS\Work/inventory
2. Scroll down to the most recent work completed (lines 53 - 66)
3. See data in columns for Start Time (column H) and Duration Time (column I)

**Expected behavior**
The expected behavior is that both start and duration times are written out as hours:minutes:seconds, foe example start time 00:23:10 and duration time 03:15. 

**Error message or screenshots**
If applicable, copy the error message or add screenshots to help explain your problem.

**Impact on your work**
This bug is affecting my work because the data cohesive with the previous clips made. 

**Additional context**

**Comment by bonniegee** [comment]
The timecode appears as a decimal when the csv file is opened in Excel. When the csv is opened in a text editor, the timecode displays as expected (hh:mm:ss). Therefore, the issue is not in the output of the script but in how the data is rendered in Excel; more testing needs to be done to see why this is happening and fix the issue.
