### ISSUE TITLE
extractClipGetInfo gone

### ISSUE THREAD

**Issue by Stuartacus** [RockefellerArchiveCenter/scripts#87]
extractClipGetInfo

Seems to have gone, but it is still referenced (also by this blog post - https://saaers.wordpress.com/2018/10/30/using-python-ffmpeg-and-the-archivesspace-api-to-create-a-lightweight-clip-library/

Is it still available.

S

**Comment by helrond** [comment]
Hi @Stuartacus - we removed that script because we don't use it anymore. That said, because of version control nothing is ever truly deleted. If you go back to this commit and view the diff of that script (/archivessnake/extractClipGetInfo.py) you'll be able to see the source code: https://github.com/RockefellerArchiveCenter/scripts/commit/1bca4fd9b28be94917b5d5471c022f44dfb54624

Let me know if you have trouble, and I can find a way to get the code to you!

**Comment by Stuartacus** [comment]
Fantastic, thanks for your help. Hopefully I can get it going.

**Comment by helrond** [comment]
@Stuartacus I'm going to close this issue but if you have further questions feel free to reach out to me directly via email t harnold@rockarch.org.
